[package]

name = "libmarisa-sys"
version = "0.0.1"
authors = ["Alexander Polakov <plhk@sdf.org>"]
links = "marisa"
build = "build.rs"

[build-dependencies]
gcc = "0.3.1"

[build-dependencies.libstdcpp-sys]
git = "https://github.com/polachok/libstdcpp-sys"


